<?xml version="1.0" encoding="utf-8"?><Database Name="QL_QuanCafe" Class="QLCAFEDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-PLG7HV2\SQLEXPRESS;Initial Catalog=QL_QuanCafe;Integrated Security=True" SettingsObjectName="DoAn_QLCAFE.Properties.Settings" SettingsPropertyName="QL_QuanCafeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="MACTHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MAHOADON" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MAMON" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="THUCDON_CHITIETHOADON" Member="THUCDON" ThisKey="MAMON" OtherKey="MAMON" Type="THUCDON" IsForeignKey="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="HOADON" ThisKey="MAHOADON" OtherKey="MAHOADON" Type="HOADON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THUCDON" Member="THUCDONs">
    <Type Name="THUCDON">
      <Column Name="MAMON" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENMON" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MALOAI" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(90)" CanBeNull="true" />
      <Association Name="THUCDON_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MAMON" OtherKey="MAMON" Type="CHITIETHOADON" />
      <Association Name="THUCDON_CHITIETNHAP" Member="CHITIETNHAPs" ThisKey="MAMON" OtherKey="MAMON" Type="CHITIETNHAP" />
      <Association Name="LOAITHUCDON_THUCDON" Member="LOAITHUCDON" ThisKey="MALOAI" OtherKey="MALOAI" Type="LOAITHUCDON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETNHAP" Member="CHITIETNHAPs">
    <Type Name="CHITIETNHAP">
      <Column Name="MACTNHAP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MANHAP" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MAMON" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="THUCDON_CHITIETNHAP" Member="THUCDON" ThisKey="MAMON" OtherKey="MAMON" Type="THUCDON" IsForeignKey="true" />
      <Association Name="NHAPHANG_CHITIETNHAP" Member="NHAPHANG" ThisKey="MANHAP" OtherKey="MANHAP" Type="NHAPHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANHSACHBAN" Member="DANHSACHBANs">
    <Type Name="DANHSACHBAN">
      <Column Name="MABAN" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENBAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DANHSACHBAN_GOIMON" Member="GOIMONs" ThisKey="MABAN" OtherKey="MABAN" Type="GOIMON" />
    </Type>
  </Table>
  <Table Name="dbo.DM_ManHinh" Member="DM_ManHinhs">
    <Type Name="DM_ManHinh">
      <Column Name="MaManHinh" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenManHinh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GOIMON" Member="GOIMONs">
    <Type Name="GOIMON">
      <Column Name="MABAN" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAMON" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="DANHSACHBAN_GOIMON" Member="DANHSACHBAN" ThisKey="MABAN" OtherKey="MABAN" Type="DANHSACHBAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHOADON" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TONGTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MAHOADON" OtherKey="MAHOADON" Type="CHITIETHOADON" />
    </Type>
  </Table>
  <Table Name="dbo.LOAITHUCDON" Member="LOAITHUCDONs">
    <Type Name="LOAITHUCDON">
      <Column Name="MALOAI" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LOAITHUCDON_THUCDON" Member="THUCDONs" ThisKey="MALOAI" OtherKey="MALOAI" Type="THUCDON" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DTHOAI" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="DCHI" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="NHANVIEN_NHAPHANG" Member="NHAPHANGs" ThisKey="MANV" OtherKey="MANV" Type="NHAPHANG" />
    </Type>
  </Table>
  <Table Name="dbo.NHAPHANG" Member="NHAPHANGs">
    <Type Name="NHAPHANG">
      <Column Name="MANHAP" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYNHAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="NHAPHANG_CHITIETNHAP" Member="CHITIETNHAPs" ThisKey="MANHAP" OtherKey="MANHAP" Type="CHITIETNHAP" />
      <Association Name="NHANVIEN_NHAPHANG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NguoiDung" Member="QL_NguoiDungs">
    <Type Name="QL_NguoiDung">
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HoatDong" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NguoiDungNhomNguoiDung" Member="QL_NguoiDungNhomNguoiDungs">
    <Type Name="QL_NguoiDungNhomNguoiDung">
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhomNguoiDung" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NhomNguoiDung" Member="QL_NhomNguoiDungs">
    <Type Name="QL_NhomNguoiDung">
      <Column Name="MaNhom" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_PhanQuyen" Member="QL_PhanQuyens">
    <Type Name="QL_PhanQuyen">
      <Column Name="MaNhomNguoiDung" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaManHinh" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CoQuyen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>